apiVersion: v1
kind: BuildConfig
metadata:
  name: cotdcicdpipeline
  labels:
    name: cotdcicdpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "cotdcicd", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\n\
      \nstage '==> Build&Deploy-In-Development'\n\ 
      \nopenshiftBuild(namespace: 'development', buildConfig: 'cats', showBuildLogs: 'true')\
      \nopenshiftBuild(namespace: 'development', buildConfig: 'cities', showBuildLogs: 'true')\
      \n\nstage '==> Tag-Image-in-Development'\n\
      \nopenshiftTag(namespace: 'development', sourceStream: 'cats', sourceTag: 'latest', destinationStream: 'cats', destinationTag: 'promoteQA')\
      \nopenshiftTag(namespace: 'development', sourceStream: 'cities', sourceTag: 'latest', destinationStream: 'cities', destinationTag: 'promoteQA')\
      \n\nstage '==> Deploy&Scale-In-Testing' \n\
      \nopenshiftScale(namespace: 'testing', deploymentConfig: 'cats', replicaCount: '2')\
      \nopenshiftScale(namespace: 'testing', deploymentConfig: 'cities', replicaCount: '2')\
      \n\n}\n"
  output:
  resources:
  postCommit:
