apiVersion: v1
kind: BuildConfig
metadata:
  name: cotdcicdpipeline
  labels:
    name: cotdcicdpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "cotdcicd", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\n\
      \nstage '==> Build-In-Development'\n\ 
      \nopenshiftBuild(verbose: 'true', namespace: 'development', buildConfig: 'cats', showBuildLogs: 'true')\
      \nopenshiftBuild(verbose: 'true', namespace: 'development', buildConfig: 'cities', showBuildLogs: 'true')\
      \n\nstage '==> Deploy-In-Development'\n\
      \nopenshiftDeploy(verbose: 'true', namespace: 'development', deploymentConfig: 'cats')\ 
      \nopenshiftScale(verbose: 'true', namespace: 'development', deploymentConfig: 'cats', replicaCount: '1')\
      \nopenshiftDeploy(verbose: 'true', namespace: 'development', deploymentConfig: 'cities')\
      \nopenshiftScale(verbose: 'true', namespace: 'development', deploymentConfig: 'cities', replicaCount: '1')\
      \n\nstage '==> Tag-Image-in-Development'\n\
      \nopenshiftTag(verbose: 'true', namespace: 'development', sourceStream: 'cats', sourceTag: 'latest', destinationStream: 'cats', destinationTag: 'promoteToQA')\
      \nopenshiftTag(verbose: 'true', namespace: 'development', sourceStream: 'cities', sourceTag: 'latest', destinationStream: 'cities', destinationTag: 'promoteToQA')\
      \n\nstage '==> Deploy-In-Testing' \n\
      \nopenshiftDeploy(verbose: 'true', namespace: 'testing', deploymentConfig: 'cats', )\
      \nopenshiftScale(verbose: 'true', namespace: 'testing', deploymentConfig: 'cats', replicaCount: '2')\
      \nopenshiftDeploy(verbose: 'true', namespace: 'testing', deploymentConfig: 'cities', )\
      \nopenshiftScale(verbose: 'true', namespace: 'testing', deploymentConfig: 'cities', replicaCount: '2')\
      \n\n}\n"
  output:
  resources:
  postCommit:
