apiVersion: v1
kind: BuildConfig
metadata:
  name: cotdpipeline
  labels:
    name: cotdpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "cotd", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'build'\nopenshiftBuild(namespace: 'development', buildConfig: 'cotd', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'cotd')\nopenshiftScale(deploymentConfig: 'cotd',replicaCount: '2')\n}"
  output:
  resources:
  postCommit:
