apiVersion: v1
kind: BuildConfig
metadata:
  name: testpipeline
  labels:
    name: testpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "testphp", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage '==>Build'\nopenshiftBuild(namespace: 'development', buildConfig: 'cotd', showBuildLogs: 'true')\nstage '==>Deploy'\nopenshiftDeploy(namespace: 'development', deploymentConfig: 'cotd')\nopenshiftScale(namespace: 'development', deploymentConfig: 'cotd',replicaCount: '2')\n}"
  output:
  resources:
  postCommit: